services:
  gmail-relay:
    image: docker.io/takuya/postfix-gmail-smtp-for-oauth
    container_name: gmail-relay
    restart: unless-stopped
    ports:
      - "2525:25"
    env_file:
      - ./google-oauth/gmail.env

